[package]
name = "lambda"
version = "0.1.0"
authors = ["zachwood0s <zach@hayzak.com>"]

[dependencies]
clap = "~2.33"
colored = "1.7"
dialoguer = { git = "https://github.com/zachwood0s/dialoguer.git" }
